import { useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { LogIn, LayoutDashboard } from "lucide-react";
import { joinRoomByCode } from "../api/roomService";

// Standalone "join a room" page, reachable directly via an invite link
// like /join/AB12CD (the link generated by the "Copy Invite Link"
// buttons on the dashboard and in the workspace Topbar), or via /join
// with the code typed in manually.
export default function JoinRoom() {
  const { code: codeFromUrl } = useParams();
  const [code, setCode] = useState(codeFromUrl ? codeFromUrl.toUpperCase() : "");
  const [error, setError] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const navigate = useNavigate();

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!code.trim()) return;

    setError("");
    setSubmitting(true);
    try {
      const data = await joinRoomByCode(code.trim().toUpperCase());
      navigate(`/workspace/${data.room._id}`);
    } catch (err) {
      setError(err.response?.data?.message || "Could not validate that room code");
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="min-h-screen bg-gray-100 dark:bg-gray-950 flex items-center justify-center px-4 transition-colors">
      <div className="w-full max-w-sm bg-white dark:bg-gray-900 rounded-xl border border-gray-200 dark:border-gray-800 p-8 shadow-sm">
        <div className="flex items-center gap-2 mb-6">
          <div className="bg-gradient-to-br from-violet-600 to-indigo-600 p-1.5 rounded-md">
            <LayoutDashboard size={18} className="text-white" />
          </div>
          <span className="font-bold text-lg text-gray-900 dark:text-white">SyncSpace</span>
        </div>

        <h1 className="text-lg font-semibold text-gray-900 dark:text-white mb-1">Join a Room</h1>
        <p className="text-sm text-gray-500 dark:text-gray-400 mb-6">
          Enter the room code you were given, or use an invite link.
        </p>

        {error && (
          <div className="mb-4 rounded-md bg-red-50 dark:bg-red-950/30 border border-red-200 dark:border-red-900/50 px-4 py-2 text-sm text-red-700 dark:text-red-300">
            {error}
          </div>
        )}

        <form onSubmit={handleSubmit} className="space-y-4">
          <input
            type="text"
            placeholder="Enter room code (e.g. AB12CD)"
            value={code}
            onChange={(e) => setCode(e.target.value)}
            autoFocus
            className="block w-full rounded-lg border border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100 px-3 py-2.5 placeholder-gray-400 shadow-sm focus:border-violet-500 focus:outline-none focus:ring-1 focus:ring-violet-500 sm:text-sm uppercase tracking-wider"
          />
          <button
            type="submit"
            disabled={submitting}
            className="w-full bg-gradient-to-r from-violet-600 to-indigo-600 hover:brightness-110 text-white px-4 py-2.5 rounded-lg text-sm font-medium transition disabled:opacity-60 flex items-center justify-center gap-2"
          >
            <LogIn size={16} />
            {submitting ? "Validating..." : "Join Room"}
          </button>
        </form>

        <button
          onClick={() => navigate("/")}
          className="mt-4 w-full text-center text-sm text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-200"
        >
          Back to dashboard
        </button>
      </div>
    </div>
  );
}
